---
title: "Chembl 21 Inhibitors Prediction"
author: Saw Simeon, Nuttapat Anuwongcharoen, Watshara Shoombuatong, Aijaz Ahmad Malik,
  Virapong Prachayasittikul, Jarl E. S. Wikberg and Chanin Nantasenamat
date: "June 24, 2559 BE"
output: pdf_document
---

## Function for Reading external data set

```{r, tidy = TRUE}
read_file <- function(x) {
  library(data.table)
  data <- fread(x)
  IC50_nm <- data$IC50
  IC50 <- as.numeric(IC50_nm)*10^-9
  pIC50 <- -log10(IC50)
  data <- as.data.frame(data)
  curated_data <- cbind(pIC50, data)
  return(curated_data)
}

```

## Importing new AchE inhibitors from Chembl 21 

```{r, tidy = TRUE}

AtomPairs2D_fingerPrintCount <- read_file("data_Chembl_21/2D_Atom_Paris_Count.csv")
AtomPairs2D_fingerPrinter <- read_file("data_Chembl_21/2D_Atom_Pairs.csv")
Substructure_fingerPrintCount <- read_file("data_Chembl_21/Substructure_Count.csv")
Substructure_fingerPrinter <- read_file("data_Chembl_21/Substructure.csv")
Extended_finterPrinter <- read_file("data_Chembl_21/CDK_Extended.csv")
FingerPrinter <- read_file("data_Chembl_21/CDK.csv")
Estate_FingerPrinter <- read_file("data_Chembl_21/E_State.csv")
GraphOnly_FingerPrinter <- read_file("data_Chembl_21/CDK_Graph_Only.csv")
KlekotaRoth_FingerprintCount <- read_file("data_Chembl_21/Klekota_Roth_Count.csv")
KlekotaRoth_FingerPrinter <- read_file("data_Chembl_21/Klekota_Roth.csv")
MACCS_FingerPrinter <- read_file("data_Chembl_21/MACCS.csv")
Pubchem_FingerPrinter <- read_file("data_Chembl_21/PubChem.csv")


external <- list(AtomPairs2D_fingerPrintCount=AtomPairs2D_fingerPrintCount,
              AtomPairs2D_fingerPrinter = AtomPairs2D_fingerPrinter,
              Substructure_fingerPrintCount = Substructure_fingerPrintCount,
              Substructure_fingerPrinter = Substructure_fingerPrinter,
              Extended_finterPrinter = Extended_finterPrinter,
              FingerPrinter = FingerPrinter,
              Estate_FingerPrinter = Estate_FingerPrinter,
              GraphOnly_FingerPrinter = GraphOnly_FingerPrinter,
              KlekotaRoth_FingerprintCount = KlekotaRoth_FingerprintCount,
              KlekotaRoth_FingerPrinter = KlekotaRoth_FingerPrinter,
              MACCS_FingerPrinter = MACCS_FingerPrinter,
              Pubchem_FingerPrinter = Pubchem_FingerPrinter)

```

```{r, tidy = TRUE}

randomForest_testing <- function(train, test){
  library(parallel)
  library(doSNOW)
  cl <- makeCluster(8)
  registerDoSNOW(cl)

  R2 <- function(y, equation, ... ){
  1 - (sum((y-predict(equation))^2)/sum((y-mean(y))^2))
}
rm2 <- function(y, x, ... ){  
  if ((R2(y,(lm(y ~ x)))) > R2(y,(lm(y ~ -1 + x)))) { 
    return(R2(y,(lm(y ~ x)))*( 1-(sqrt(R2(y,(lm(y ~ x)))-R2(y,(lm(y ~ -1 + x)))))))
  } else { 
    return(R2(y,(lm(y ~ x))))
  } 
}
rm2.reverse <- function(y, x, ... ){
  return(R2(x,(lm(x ~ y)))*( 1-(sqrt(R2(x,(lm(x ~ y)))-R2(x,(lm(x ~ -1 + y)))))))
}
average.rm2 <- function(y, x, ... ){
  if ((R2(y,(lm(y ~ x)))) > R2(y,(lm(y ~ -1 + x)))) {
    return(((R2(y,(lm(y ~ x)))*( 1-(sqrt(R2(y,(lm(y ~ x)))-R2(y,(lm(y ~ -1 + x))))))+ R2(x,(lm(x ~ y)))*( 1-(sqrt(R2(x,(lm(x ~ y)))-R2(x,(lm(x ~ -1 + y))))))))/2)
  } else { 
    return(((R2(y,(lm(y ~ x))))  + (R2(x,(lm(x ~ y)))*( 1-(sqrt(R2(x,(lm(x ~ y)))-R2(x,(lm(x ~ -1 + y)))))))  )/2)
  }
}
delta.rm2 <- function(y, x, ... ){
  if ((R2(y,(lm(y ~ x)))) > R2(y,(lm(y ~ -1 + x)))) {
    return(abs((R2(y,(lm(y ~ x)))*( 1-(sqrt(R2(y,(lm(y ~ x)))-R2(y,(lm(y ~ -1 + x))))))  -  R2(x,(lm(x ~ y)))*( 1-(sqrt(R2(x,(lm(x ~ y)))-R2(x,(lm(x ~ -1 + y)))))))))
  } else { 
    return(abs((R2(y,(lm(y ~ x)))) - (R2(x,(lm(x ~ y)))*( 1-(sqrt(R2(x,(lm(x ~ y)))-R2(x,(lm(x ~ -1 + y)))))))  ))
  }
}


  results <- list(100)
  results <- foreach(i = 1:100 ) %dopar% {

    x <- na.omit(train)
    para <- dplyr::sample_n(x, size = 2570, replace = TRUE)
    in_train_para <- sample(nrow(para),
                            size = as.integer(nrow(para) * 0.8),
                            replace = FALSE)
    Train <- para[in_train_para, ]
    unused <- para[-in_train_para, ]
    rm(unused)
    des <- Train[, 2:ncol(Train)]
    name <- names(des)
    Test <- test
    pIC50 <- Test$pIC50
    Test <- Test[, name]
    
    model_train <- ranger::ranger(pIC50~., data = Train, write.forest = TRUE, save.memory = TRUE)
    #actual <- train$Activity
    prediction <- predict(model_train, Test)
    prediction <- prediction$predictions
    value <- data.frame(obs = pIC50, pred = prediction)
    rm(Train)
    rm(Test)
    rm(para)
    rm(in_train_para)
    rm(prediction)
    labeling <- c("obs", "pred")
    colnames(value) <- labeling
    result <- caret::defaultSummary(value)
    result_rm2 <- rm2(value$obs, value$pred)
    names(result_rm2) <- "rm2"
    results_reverse <- rm2.reverse(value$obs, value$pred)
    names(results_reverse) <- "reverse.rm2"
    result_average_rm2 <- average.rm2(value$obs, value$pred)
    names(result_average_rm2) <- "average.rm2"
    result_delta <- delta.rm2(value$obs, value$pred)
    names(result_delta) <- "delta.rm"

    results[[i]] <- c(result, result_rm2, results_reverse, result_average_rm2, result_delta)
  }
  return(results)
  stopCluster(cl)
}

mean_and_sd <- function(x) {
  c(round(rowMeans(x, na.rm = TRUE), digits = 2),
    round(genefilter::rowSds(x, na.rm = TRUE), digits = 2))
}

randomForest_test <- function(train, test) {
  ok <- randomForest_testing(train, test)
  data <- data.frame(ok)
  result <- mean_and_sd(data)
  df <- data.frame(result)
  R2_and_RMSE <- t(df)
  label <- c("RMSE_Mean", "Rsquared_Mean", "RM2_Mean", "Reverse_RM2_Mean", "Average_RM2_Mean", "Delta_RM2_Mean",
             "RMSE_SD", "Rsquared_SD", "RM2_SD", "Reverse_RM2_SD", "Average_RM2_SD", "Delta_RM2_SD")
  colnames(R2_and_RMSE) <- label
  return(R2_and_RMSE)
}

```

## Prediction New AChE Inhibitors from Chembl 21 using Training Data Set from Chembl20

```{r, tidy = TRUE, warning=TRUE, error=TRUE, message=TRUE}

training <- readRDS("data.Rds")
testing <- readRDS("Chembl_21.Rds")

data_frames <- c("AtomPairs2D_fingerPrintCount", "AtomPairs2D_fingerPrinter", "Substructure_fingerPrintCount",
         "Substructure_fingerPrinter", "Extended_finterPrinter", "FingerPrinter", "Estate_FingerPrinter",
         "GraphOnly_FingerPrinter", "KlekotaRoth_FingerprintCount", "KlekotaRoth_FingerPrinter",
         "MACCS_FingerPrinter", "Pubchem_FingerPrinter")

results <- list()

for (i in data_frames) {
  train <- as.data.frame(training[[i]])
  test <- as.data.frame(testing[[i]])
  result <- randomForest_test(train, test)
  results[[i]] <- result
}

results
```
